name = "StaTech Industry 2.0"
author = "Static Void, Purple Dino, & GronkDev"
version = "2.0.0rc1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b6ca7972bb11687070f7127a251f4b86987b84beac9b727e5b1606f29e215bf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.242"
