name = "StaTech Industry 2.0"
author = "Static Void, Purple Dino, & GronkDev"
version = "0.3.0b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a767609a8d1eed5a64a914f94e59d66a91bc6bfbf6bf96784a1ea4ec15f9646"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
