name = "StaTech Industry 2.0"
author = "Static Void, Purple Dino, & GronkDev"
version = "2.0.0rc1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce64a7a64c8234007d6147b44bc2515cf28e2048753cd0867e356c82899a7657"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.238"
