
#General Config Section. See https://srpc.fdd-docs.com/introduction/
[general]
	#The Application ID of the Discord App to use
	applicationID = "1533840410483495193"
	#Enable/Disable the mod
	enabled = true
	#Enable/Disable debugging mode. WARNING: MAY CAUSE LOG SPAM!
	debugging = false
	#Enable the detection of certain compatible launchers, allowing you to use their name and icon in your config
	launcherIntegration = false
	#Allow using local image files, as RPC icons
	rpcImageServer = false
	#The URL of the RPC image server that will be used for local images. Restart required when changed
	rpcImageServerUrl = "https://rpcavatar.firstdark.dev"
	#Internal Version Number. NO TOUCHY!
	version = 27

#The Game Loading event
[init]
	#Enable/Disable the Game Loading Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[init.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = "StaTech Industry 2 is loading"
		#The second line of text under the app name
		state = "Game Starting..."
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["mclogonew"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "It's StaTech Industry 2 {{game.version}}, but modded"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["mclogo"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "{{game.mods}} mods installed"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"
		#List of buttons (max 2) to show on the RPC
		buttons = []

#The Main Menu event
[main_menu]
	#Enable/Disable the Main Menu Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[main_menu.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = "{{player.name}} is currently lazy"
		#The second line of text under the app name
		state = "Chilling in the menu"
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["mclogonew"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "It's StaTech Industry 2 {{game.version}}, but modded"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["{{images.player}}"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "{{player.name}}"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"
		#List of buttons (max 2) to show on the RPC
		buttons = []

#The Server List event
[server_list]
	#Enable/Disable the Server List Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[server_list.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = "{{player.name}} is looking for a server"
		#The second line of text under the app name
		state = "Searching for friends"
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["mclogonew"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "It's StaTech Industry 2 {{game.version}}, but modded"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["{{images.player}}"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "{{player.name}}"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"
		#List of buttons (max 2) to show on the RPC
		buttons = []

#The Realms Screen event
[realms_list]
	#Enable/Disable the Realms Screen Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[realms_list.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = "{{player.name}} is looking for a Realm"
		#The second line of text under the app name
		state = "Browsing Realms"
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["mclogonew"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "It's StaTech Industry 2 {{game.version}}, but modded"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["{{images.player}}"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "{{player.name}}"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"
		#List of buttons (max 2) to show on the RPC
		buttons = []

#The Join Game Event
[join_game]
	#Enable/Disable the Join Game Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[join_game.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = "{{player.name}} is joining a game"
		#The second line of text under the app name
		state = "Joining Game"
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["mclogonew"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "It's StaTech Industry 2 {{game.version}}, but modded"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["{{images.player}}"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "{{player.name}}"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"
		#List of buttons (max 2) to show on the RPC
		buttons = []

#The Single Player Event
[single_player]
	#Enable/Disable the Single Player Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[single_player.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = "Currently In {{world.name}}"
		#The second line of text under the app name
		state = "Playing lonely mode"
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["mclogonew"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "It's StaTech Industry 2 {{game.version}}, but modded"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["{{images.player}}"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "{{player.name}}"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"
		#List of buttons (max 2) to show on the RPC
		buttons = []

#The Multi Player Event
[multi_player]
	#Enable/Disable the Multi Player Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[multi_player.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = "Playing on {{server.name}} with {{server.players.count}} players"
		#The second line of text under the app name
		state = "Playing online"
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["mclogonew"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "It's StaTech Industry 2 {{game.version}}, but modded"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["{{images.player}}"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "{{player.name}}"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"
		#List of buttons (max 2) to show on the RPC
		buttons = []

#The Realms Game Event
[realms]
	#Enable/Disable the Realms Game Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[realms.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = "Playing on {{realm.name}}"
		#The second line of text under the app name
		state = "Playing on a Realm"
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["mclogonew"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "It's StaTech Industry 2 {{game.version}}, but modded"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["{{images.player}}"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "{{player.name}}"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"
		#List of buttons (max 2) to show on the RPC
		buttons = []

#The Paused Event
[paused]
	#Enable/Disable the Pause Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[paused.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = "In the Pause Menu"
		#The second line of text under the app name
		state = "Game Paused"
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["mclogonew"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "It's StaTech Industry 2 {{game.version}}, but modded"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["{{images.player}}"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "{{player.name}}"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"
		#List of buttons (max 2) to show on the RPC
		buttons = []

#Fallback event for disabled events
[generic]

	#List of RPCs that will be displayed at random
	[[generic.presence]]
		#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
		type = "PLAYING"
		#The first line of text under the app name
		description = "Playing StaTech Industry 2"
		#The second line of text under the app name
		state = ""
		#The Asset ID or URLs of images to randomly use for the large image
		largeImageKey = ["mclogonew"]
		#The text to show when someone hovers over the largeImage
		largeImageText = "It's StaTech Industry 2 {{game.version}}, but modded"
		#The Asset ID or URLs of images to randomly use for the small image
		smallImageKey = ["mclogo"]
		#The text to show when someone hovers over the smallImage
		smallImageText = "{{game.mods}} mods installed"
		#The Twitch or Youtube URL to use when type is set to STREAMING
		streamingActivityUrl = "https://twitch.tv/twitch"
		#List of buttons (max 2) to show on the RPC
		buttons = []

#Custom Config Variables that you can use
[custom]
	#Must these variables be parsed along with other variables
	enabled = true
	#Your custom variables to add
	variables = []

#Dimension Information Overrides
[dimension_overrides]
	#Allows you to override the displayed values for dimensions
	enabled = false

	#The Dimensions to override
	[[dimension_overrides.dimensions]]
		#The name of the Dimension/Biome to override. FORMAT: modid:dimension or modid:biome
		name = "overworld"

		#List of RPCs that will be displayed at random
		[[dimension_overrides.dimensions.presence]]
			#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
			type = "PLAYING"
			#The first line of text under the app name
			description = "{{player.name}} is in The Overworld"
			#The second line of text under the app name
			state = ""
			#The Asset ID or URLs of images to randomly use for the large image
			largeImageKey = ["overworld"]
			#The text to show when someone hovers over the largeImage
			largeImageText = "In the Overworld"
			#The Asset ID or URLs of images to randomly use for the small image
			smallImageKey = ["mclogo"]
			#The text to show when someone hovers over the smallImage
			smallImageText = "{{game.mods}} mods installed"
			#The Twitch or Youtube URL to use when type is set to STREAMING
			streamingActivityUrl = "https://twitch.tv/twitch"
			#List of buttons (max 2) to show on the RPC
			buttons = []

	[[dimension_overrides.dimensions]]
		#The name of the Dimension/Biome to override. FORMAT: modid:dimension or modid:biome
		name = "the_nether"

		#List of RPCs that will be displayed at random
		[[dimension_overrides.dimensions.presence]]
			#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
			type = "PLAYING"
			#The first line of text under the app name
			description = "{{player.name}} is in The Nether"
			#The second line of text under the app name
			state = ""
			#The Asset ID or URLs of images to randomly use for the large image
			largeImageKey = ["nether"]
			#The text to show when someone hovers over the largeImage
			largeImageText = "In the Nether"
			#The Asset ID or URLs of images to randomly use for the small image
			smallImageKey = ["mclogo"]
			#The text to show when someone hovers over the smallImage
			smallImageText = "{{game.mods}} mods installed"
			#The Twitch or Youtube URL to use when type is set to STREAMING
			streamingActivityUrl = "https://twitch.tv/twitch"
			#List of buttons (max 2) to show on the RPC
			buttons = []

	[[dimension_overrides.dimensions]]
		#The name of the Dimension/Biome to override. FORMAT: modid:dimension or modid:biome
		name = "the_end"

		#List of RPCs that will be displayed at random
		[[dimension_overrides.dimensions.presence]]
			#The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
			type = "PLAYING"
			#The first line of text under the app name
			description = "{{player.name}} is in The End"
			#The second line of text under the app name
			state = ""
			#The Asset ID or URLs of images to randomly use for the large image
			largeImageKey = ["end"]
			#The text to show when someone hovers over the largeImage
			largeImageText = "In the End"
			#The Asset ID or URLs of images to randomly use for the small image
			smallImageKey = ["mclogo"]
			#The text to show when someone hovers over the smallImage
			smallImageText = "{{game.mods}} mods installed"
			#The Twitch or Youtube URL to use when type is set to STREAMING
			streamingActivityUrl = "https://twitch.tv/twitch"
			#List of buttons (max 2) to show on the RPC
			buttons = []

