// -----------------------------------------
// CREATED BY STATIC FOR USE IN
// STATECH INDUSTRY 2
// -----------------------------------------

// This list is a modified version from the AOF6 modpack
ServerEvents.tags('item', (event) => {
    const ITEMS = [
        kj('angel_ring'),
        ae('quantum_entangled_singularity'),
        ae('spatial_storage_cell_2'),
        ae('spatial_storage_cell_16'),
        ae('spatial_storage_cell_128'),
        ae('sky_stone_tank'),
        ae('portable_item_cell_1k'),
        ae('portable_item_cell_4k'),
        ae('portable_item_cell_16k'),
        ae('portable_item_cell_64k'),
        ae('portable_item_cell_256k'),
        ae('portable_fluid_cell_1k'),
        ae('portable_fluid_cell_4k'),
        ae('portable_fluid_cell_16k'),
        ae('portable_fluid_cell_64k'),
        ae('portable_fluid_cell_256k'),
        ae('item_storage_cell_1k'),
        ae('item_storage_cell_4k'),
        ae('item_storage_cell_16k'),
        ae('item_storage_cell_64k'),
        ae('item_storage_cell_256k'),
        ae('fluid_storage_cell_1k'),
        ae('fluid_storage_cell_4k'),
        ae('fluid_storage_cell_16k'),
        ae('fluid_storage_cell_64k'),
        ae('fluid_storage_cell_256k'),
        ar('everlasting_beef'),
        ar('eternal_steak'),
        su('safe'),
        cr('chest_minecart_contraption'),
        cr('furnace_minecart_contraption'),
        cr('minecart_contraption'),
        ae('wireless_crafting_terminal'),
        sp('omni_accelerator'),
        sp('knowledge_gem'),
        sp('bottomless_bundle'),
        sp('laurels_of_serenity'),
        sp('ring_of_aerial_grace'),
        sp('gloves_of_dawns_grasp'),
        sp('heartsingers_reward'),
        sp('shieldgrasp_amulet'),
        sp('present'),
        sp('ring_of_pursuit'),
        sp('ring_of_denser_steps'),
        sp('shieldgrasp_amulet'),
        ea('void_cell'),
        ea('package'),
        bae('quantum_item_storage_cell'),
        bae('quantum_fluid_storage_cell'),
        gag('time_sand_pouch'),
        xp('experience_obelisk'),
        ei('processing_array'),
        io('multi_processing_array'),
        /megacells:.*cell.*/,
        /megacells:.*crafting_storage.*/,
        ch('chisel'),
        '#spectrum:ink_containers',
        '#c:shulker_boxes',
        '#modern_industrialization:tanks',
        '#create:toolboxes',
        '#create:postboxes',
        '#create:packages',
        '#supplementaries:presents',
        '#supplementaries:trapped_presents',
    ];

    ITEMS.forEach((id) => event.add(mi('replicator_blacklist'), id));
});
