// -----------------------------------------
// CREATED BY STATIC FOR USE IN
// STATECH INDUSTRY 2
// -----------------------------------------

ServerEvents.recipes((event) => {
    // -- MOD NAMESPACE UTILITY FUNCTIONS -- //
    let st = (id) => `statech:modern_industrialization/recycler/${id}`;

    // -- LOW TIER SCRAP -- //
    recycler(
        event,
        st('low_tier_scrap'),
        2,
        50,
        [{ amount: 1, tag: 'statech:scrappable/low' }],
        [{ amount: 1, item: kj('scrap'), probability: 0.35 }]
    );

    // -- MID TIER SCRAP -- //
    recycler(
        event,
        st('mid_tier_scrap'),
        4,
        50,
        [{ amount: 1, tag: 'statech:scrappable/mid' }],
        [{ amount: 2, item: kj('scrap'), probability: 0.5 }]
    );

    // -- HIGH TIER SCRAP -- //
    recycler(
        event,
        st('high_tier_scrap'),
        8,
        50,
        [{ amount: 1, tag: 'statech:scrappable/high' }],
        [{ amount: 3, item: kj('scrap'), probability: 0.8 }]
    );
});

ServerEvents.tags('item', (event) => {
    // -- MOD NAMESPACE UTILITY FUNCTIONS -- //
    let st = (id) => `statech:scrappable/${id}`;

    let LOW_TIER_SCRAP = [
        /^chisel:.*(planks|concrete|bricks|wool|stone).*/,
        /^nomansland:.*(stone|silt|brick|barrel).*/,
        /^ae2:.*(quartz|paint|sky_stone).*/,
        /^minecraft:.*(oxidized|waxed|weathered|coral|basalt|bamboo|tuff|blackstone).*/,
        /^modern_industrialization:.*(bucket).*/,
        mc('lapis_lazuli'),
        mc('fire_charge'),
        mc('wind_charge'),
        mc('flint'),
        mc('glass_bottle'),
        mc('bowl'),
        mc('paper'),
        mc('book'),
        mc('ink_sac'),
        mc('honeycomb'),
        mc('charcoal'),
        mc('dried_kelp'),
        mc('bread'),
        mc('baked_potato'),
        mc('poisonous_potato'),
        ea('entro_shard'),
        mc('blaze_powder'),
        ea('entro_seed'),
        mc('apple'),
        mc('melon_slice'),
        nm('pear'),
        nm('pine_nuts'),
        nm('walnuts'),
        nm('trail_mix'),
        '#minecraft:coals',
        '#c:ores/iron',
        '#c:ores/coal',
        '#c:ores/lignite_coal',
        '#c:ores/copper',
        '#c:ores/tin',
        '#c:ores/gold',
        '#c:ores/redstone',
        '#c:ores/quartz',
        '#c:ores/iron',
        '#c:ores/zinc',
        '#c:ores/salt',
        '#c:ores/antimony',
        '#c:ores/fluorite',
        '#c:ores/lapis',
        '#c:ores/lead',
        '#c:ores/nickel',
        '#c:cobblestones',
        '#minecraft:arrows',
        '#minecraft:rails',
        '#minecraft:logs',
        '#minecraft:planks',
        '#minecraft:doors',
        '#minecraft:trapdoors',
        '#minecraft:fences',
        '#minecraft:fence_gates',
        '#minecraft:buttons',
        '#minecraft:pressure_plates',
        '#minecraft:slabs',
        '#minecraft:stairs',
        '#minecraft:leaves',
        '#minecraft:dirt',
        '#minecraft:sand',
        '#minecraft:beds',
        '#minecraft:candles',
        '#minecraft:banners',
        '#minecraft:wool',
        '#minecraft:flowers',
        '#minecraft:meat',
        '#minecraft:fishes',
        '#minecraft:saplings',
        '#minecraft:walls',
        '#minecraft:terracotta',
        '#minecraft:signs',
        '#minecraft:hanging_signs',
        '#minecraft:wool_carpets',
        '#minecraft:wooden_pressure_plates',
        '#minecraft:soul_fire_base_blocks',
        '#minecraft:boats',
        '#supplementaries:way_signs',
        '#supplementaries:flags',
        '#supplementaries:buntings',
        '#supplementaries:awnings',
        '#supplementaries:candle_holders',
        '#supplementaries:presents',
        '#supplementaries:trapped_presents',
        '#luminax:blocks',
        '#luminax:dim_blocks',
        '#luminax:pressure_plates',
        '#luminax:dim_pressure_plates',
        '#factory_blocks:factory_blocks',
        '#architects_palette:nubs',
        '#architects_palette:boards',
        '#nomansland:offering/bricks',
        '#c:fence_gates',
        '#c:bookshelves',
        '#c:silicon',
        '#c:ices',
        '#c:seeds',
        '#c:stones',
        '#c:netherracks',
        '#c:gravels',
        '#c:end_stones',
        '#c:sandstone/blocks',
        '#c:concrete_powders',
        '#c:smooth_stone',
        '#c:foods/vegetable',
        '#c:crops',
        '#c:foods/raw_fish',
        '#c:foods/cooked_fish',
        '#c:foods/cooked_egg',
        '#c:foods/soup',
        '#c:foods/pie',
        '#c:foods/cookie',
        '#c:foods/candy',
        '#c:pumpkins',
        '#c:animal_foods',
        '#c:dyes',
        '#c:eggs',
        '#c:glazed_terracottas',
        '#c:concretes',
        '#c:glass_blocks',
        '#c:glass_panes',
        '#c:cobblestones',
        '#c:raw_materials',
        '#c:dusts',
        '#c:nuggets',
        '#c:bolts',
        '#c:rings',
        '#c:blades',
        '#c:tiny_dusts',
        '#c:rods',
        '#c:wires',
        '#c:chains',
        '#c:feathers',
        '#c:bones',
        '#c:gunpowders',
        '#c:strings',
        '#c:leathers',
        '#c:fertilizers',
        '#c:buckets',
        '#chisel:chiseled_ice',
        '#chisel:chiseled_nether_brick',
        '#chisel:chiseled_purpur',
        '#chisel:chiseled_quartz',
        '#chisel:chiseled_prismarine',
        '#chisel:chiseled_glass',
        '#chisel:chiseled_andesite',
        '#chisel:chiseled_deepslate',
        '#chisel:chiseled_diorite',
        '#chisel:chiseled_granite',
        '#chisel:chiseled_dirt',
        '@comforts',
        '@createdeco',
        '@iden_decor',
        '@industrially_plated',
        '@xtonesreworked',
        '@framedblocks',
        '@simplylight',
        '@decorativeblocks',
        '@architects_palette',
        '@elevatorid',
    ];
    LOW_TIER_SCRAP.forEach((id) => {
        event.add(st('low'), id);
    });

    let MID_TIER_SCRAP = [
        ea('entro_crystal'),
        mc('ender_eye'),
        mc('dragon_breath'),
        mc('fermented_spider_eye'),
        mc('rabbit_foot'),
        mc('glistening_melon'),
        mc('magma_cream'),
        mc('ghast_tear'),
        mc('phantom_membrane'),
        mc('shulker_shell'),
        mc('chorus_fruit'),
        mc('popped_chorus_fruit'),
        mc('glow_ink_sac'),
        mc('ender_pearl'),
        mc('diamond'),
        mc('emerald'),
        mc('prismarine_crystals'),
        mc('prismarine_shard'),
        mc('amethyst'),
        mc('amethyst_block'),
        mi('peridot'),
        mi('ruby'),
        mi('sapphire'),
        mi('rubber_sheet'),
        mc('copper_block'),
        mc('raw_copper_block'),
        mc('copper_grate'),
        mc('copper_bulb'),
        mc('chiseled_copper'),
        mc('cut_copper'),
        /^ae2:.*(fluix|card|circuit|processor|press).*/,
        '#little_big_redstone:logic_arrays',
        '#little_big_redstone:floppy_disks',
        '#little_big_redstone:microchips',
        '#c:obsidians',
        /^chisel:.*(iron_block|gold_block|lapis_block).*/,
        '#c:potions',
        '#c:foods/edible_when_placed',
        '#farmersdelight:feasts',
        '#minecraft:skulls',
        '#c:armors',
        '#modern_industrialization:fluid_pipes',
        '#modern_industrialization:item_pipes',
        '#modern_industrialization:me_wires',
        '#c:plates',
        '#c:curved_plates',
        '#c:ingots',
        '#c:double_ingots',
        '#c:gears',
        '#c:drill_heads',
        '#c:rotors',
        '#c:large_plates',
        '@waystones',
        '#c:ores/ruby',
        '#c:ores/sapphire',
        '#c:ores/kernite',
        '#c:ores/bauxite',
        '#c:ores/emerald',
        '#c:ores/peridot',
        '#c:ores/emerald',
        '#c:ores/fluorite',
        '#c:ores/diamond',
    ];
    MID_TIER_SCRAP.forEach((id) => {
        event.add(st('mid'), id);
    });

    let HIGH_TIER_SCRAP = [
        /^chisel:.*(diamond|emerald).*/,
        /^minecraft:.*(enchanted|netherite).*/,
        /^modern_industrialization:.*(block|circuit|upgrade|casing|electric|hatch|coil|motor|pump).*/,
        mc('iron_block'),
        mc('gold_block'),
        mc('redstone_block'),
        mc('emerald_block'),
        mc('diamond_block'),
        mc('raw_iron_block'),
        mc('raw_gold_block'),
        mc('redstone_block'),
        '#minecraft:trim_templates',
        '#c:hot_ingots',
        '#kubejs:nuclear_fuel',
        '#kubejs:depleted_nuclear_fuel',
        '#c:music_discs',
        '#c:shulker_boxes',
        '#minecraft:decorated_pot_sherds',
        '#minecraft:anvil',
        '#c:ores/netherite_scrap',
        '#c:ores/titanium',
        '#c:ores/tungsten',
        '#c:ores/monazite',
        '#c:ores/platinum',
        '#c:ores/iridium',
        '#c:ores/uranium',
        '#c:ores/desh',
        '#c:ores/ostrum',
        '#c:ores/calorite',
        '#c:ores/moon_ice',
    ];
    HIGH_TIER_SCRAP.forEach((id) => {
        event.add(st('high'), id);
    });
});
