#!/bin/sh
set -e

# Check NPM
if ! npm -v > /dev/null; then
	echo NPM is not installed.
	exit 1
fi

# Check NPX
if ! npx -v > /dev/null; then
	echo NPX is not installed. Upgrade NPM.
	exit 1
fi

# ESLint and Prettier
lint_check() {
	npm install --silent 2> /dev/null
	CHANGED=$(git diff --name-only . | cut -d'/' -f2-)
	if ! PRETTIER_PROBLEMS=$(npx prettier $CHANGED --list-different 2>/dev/null); then
		echo Prettier has detected some problems. Fix them before committing.
		echo "$PRETTIER_PROBLEMS"
		exit 1
	fi

	if ! ESLINT_PROBLEMS=$(npx eslint); then
		echo Eslint has detected some problems. Fix them before committing.
		echo "$ESLINT_PROBLEMS"
		exit 1
	fi
}


cd kubejs
lint_check
