#.
#Packmakers' control panel for internal recipe compat
[recipes]
	#.
	#.
	#If Bulk Coloring should be enabled
	enableBulkColoring = false
	#.
	#If Bulk Freezing should be enabled
	enableBulkFreezing = false
	#.
	#If Bulk Sanding should be enabled
	enableBulkSanding = false
	#.
	#If Bulk Ending should be enabled
	enableBulkEnding = false

#.
#Dye Fluid contact coloring
[dyeFluid]
	#.
	#.
	#If Dye Fluid source blocks should color Item Entities on contact
	dyeFluidBlockContactColorsItems = false
	#.
	#If Dye Fluid source blocks should color Living Entities and their equipment on contact
	dyeFluidBlockContactColorsLivingEntities = false
	#.
	#If a Dye Fluid source block should be consumed after it successfully colors an entity
	dyeFluidBlockContactConsumesSource = false
	#.
	#If Dye Fluid from an Open Pipe should color Item Entities
	dyeFluidOpenPipeColorsItems = false
	#.
	#If Dye Fluid from an Open Pipe should color Living Entities and their equipment
	dyeFluidOpenPipeColorsLivingEntities = false

#.
#Dragon's Breath Fluid generation
[dragonBreath]
	#.
	#.
	#Amount of Dragon's Breath Fluid generated by a contained Ender Dragon every second, in mB
	# Default: 50
	# Range: 1 ~ 1000
	mobJarGenerationAmount = 50
