[animal_remodels]
	#Config changes require a restart to take effect
	#If the chicken remodel and texture variants are enabled
	chickenRemodel = false
	#If the cow remodel and texture variants are enabled
	cowRemodel = false
	#If the pig remodel and texture variants are enabled
	pigRemodel = false
	#If the rabbit remodel and texture variants are enabled
	rabbitRemodel = false
	#If the sheep remodel and texture variants are enabled
	sheepRemodel = false
	#If the squid remodel and texture variants are enabled
	squidRemodel = false
