[gear]
	#Allow gear items to have the 'enchanted glow' effect. Set to 'false' to disable the effect.
	#The way vanilla handles the effect is bugged, and it is recommended to disable this until it can be fixed
	#The bug is not harmful and some like the way the overpowered effect looks
	allow_enchanted_effect = false

[tooltip]
	#Show SGear Material tooltips on items that can be used as materials.
	show_material_tooltips = true
	#Show tooltips on parts and items that can be used as parts.
	show_part_tooltips = true
	#Tooltips are replaced with a simpler variant similar to vanilla and contains about as much information.
	vanilla_style_tooltips = false
