#Should commands work without cheats enabled? Mainly recommended for single player, otherwise all users on servers can trigger commands.
commandsCheatsDisabled = false
#Should all users receive the backup message? Disable to only have users with permission level 2 and higher receive them.
messagesForEveryone = true
