#Client-side Settings
[client]
	#Determines whether JEI and creative tab will show only one wood variant of each storage item tier. Makes creative tab and JEI lists smaller.
	showSingleWoodVariantOnly = true
	#Determines whether JEI and creative tab will show generic wood variants for copper and higher tiers. Can help with keeping these lists smaller when many compatible wood types are loaded.
	showHigherTierGenericWoodVariants = false
