#The minimum amount of XP gained from opening Lootr chests.
lootr_min_xp = 15
#The maximum amount of XP gained from opening Lootr chests.
lootr_max_xp = 20
#Should nuke explosions do block damage?
nuke_damage = true
