		["Stellar View Client Config"."General Config".client]
			#Gets rid of any rotation caused by the view center, making the space XYZ coordinates align with the XYZ directions in Minecraft
			disable_view_center_rotation = false
			#Removes Stars
			disable_stars = false
			#Makes Stars brighter
			bright_stars = true
			#Enables the use of textures for stars
			textured_stars = true
			#Enables dust cloud rendering
			dust_clouds = true
			#Specifies the max distance at which a Space Region can render
			# Default: 8
			# Range: 1 ~ 12
			space_region_render_distance = 8

		["Stellar View Client Config"."Overworld Config".client]
			#Controls how much the Overworld sky rotates when moving along the Z-axis
			# Default: 3000
			# Range: 0 ~ 3000
			overworld_z_rotation_multiplier = 3000

			["Stellar View Client Config"."Overworld Config".client.overworld]
				#Replaces the Vanilla Overworld sky with Stellar View sky
				replace_vanilla = true
				#Prioritizes config over information from resourcepacks
				config_priority = false
				#Stars will always be visible, even during daytime
				stars_always_visible = false
				#Chance of a meteor shower happening each day
				# Default: 10
				# Range: 0 ~ 100
				meteor_shower_chance = 10
				#Chance of a shooting star appearing each 1000 ticks
				# Default: 10
				# Range: 0 ~ 100
				shooting_star_chance = 10
				#Specifies Sol X offset
				# Default: 0
				# Range: -120 ~ 120
				sol_x_offset = 0
				#Specifies Sol Y offset
				# Default: 0
				# Range: -120 ~ 120
				sol_y_offset = 0
				#Specifies Sol Z offset
				# Default: 0
				# Range: -120 ~ 120
				sol_z_offset = 0
				#Specifies Sol X-axis rotation
				# Default: 0
				# Range: 0 ~ 360
				sol_x_rotation = 0
				#Specifies Sol Y-axis rotation
				# Default: 0
				# Range: 0 ~ 360
				sol_y_rotation = 0
				#Specifies Sol Z-axis rotation
				# Default: 0
				# Range: 0 ~ 360
				sol_z_rotation = 0

			["Stellar View Client Config"."Nether Config".client.nether]
				#Replaces the Vanilla Nether sky with Stellar View sky
				replace_vanilla = true
				#Prioritizes config over information from resourcepacks
				config_priority = false
				#Stars will always be visible, even during daytime
				stars_always_visible = false
				#Chance of a meteor shower happening each day
				# Default: 10
				# Range: 0 ~ 100
				meteor_shower_chance = 10
				#Chance of a shooting star appearing each 1000 ticks
				# Default: 10
				# Range: 0 ~ 100
				shooting_star_chance = 10

			["Stellar View Client Config"."End Config".client.end]
				#Replaces the Vanilla End sky with Stellar View sky
				replace_vanilla = true
				#Prioritizes config over information from resourcepacks
				config_priority = false
				#Stars will always be visible, even during daytime
				stars_always_visible = true
				#Chance of a meteor shower happening each day
				# Default: 10
				# Range: 0 ~ 100
				meteor_shower_chance = 10
				#Chance of a shooting star appearing each 1000 ticks
				# Default: 10
				# Range: 0 ~ 100
				shooting_star_chance = 10

			["Stellar View Client Config"."Twilight Forest Config".client.twilightforest]
				#Replaces the default Twilight Forest sky with Stellar View sky
				replace_default = true
				#Prioritizes config over information from resourcepacks
				config_priority = false
				#Chance of a meteor shower happening each day
				# Default: 10
				# Range: 0 ~ 100
				meteor_shower_chance = 10
				#Chance of a shooting star appearing each 1000 ticks
				# Default: 10
				# Range: 0 ~ 100
				shooting_star_chance = 10

			["Stellar View Client Config"."Aether Config".client.aether]
				#Replaces the default Aether sky with Stellar View sky
				replace_default = true
				#Prioritizes config over information from resourcepacks
				config_priority = false
				#Chance of a meteor shower happening each day
				# Default: 10
				# Range: 0 ~ 100
				meteor_shower_chance = 10
				#Chance of a shooting star appearing each 1000 ticks
				# Default: 10
				# Range: 0 ~ 100
				shooting_star_chance = 10
