# Don't change this! Version used to track needed updates.
version = 1
stopMusicOnJukeboxUse = true
creativeMusicInSurvival = true
situationalMusicInCreative = true
musicMinDelay = 0
musicMaxDelay = 600
playMusicWhenPaused = true
nowPlayingWidget = true
nowPlayingWidgetDuration = 6
showNowPlayingWidgetInPauseMenu = true
showNowPlayingWidgetOnTitleScreen = true
pauseWidgetPosition = "TOP_LEFT"
titleWidgetPosition = "TOP_LEFT"
unlockSituationalMusic = false
situationalMusicChance = 70