name: build_publish_pack
run-name: ${{ github.actor }} is building the modpack
on:
  workflow_dispatch:
  pull_request:
  branches:
    - main
  types:
    - closed
jobs:
  execute-exe:
    if: github.event.pull_request.merged == true
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: TOML Reader
        uses: SebRollen/toml-action@v1.2.0
        id: read_version
        with:
          file: 'pack.toml'
          field: 'version'

      - name: Build pack
        run: |
          .\packwiz.exe refresh
          .\packwiz.exe curseforge export -o 'StaTech_Industry-${{ steps.read_version.outputs.value }}.zip'
      - name: Upload Pack
        uses: actions/upload-artifact@v7
        with:
          name: StaTech_Industry-${{ steps.read_version.outputs.value }}.zip
          path: StaTech_Industry-${{ steps.read_version.outputs.value }}.zip
          archive: false

      - name: Build server pack
        run: |
          .\packwiz.exe curseforge export -o 'StaTech_Industry_Server-${{ steps.read_version.outputs.value }}.zip' -s 'server'
      - name: Upload Server Pack
        uses: actions/upload-artifact@v7
        with:
          name: StaTech_Industry_Server-${{ steps.read_version.outputs.value }}.zip
          path: StaTech_Industry_Server-${{ steps.read_version.outputs.value }}.zip
          archive: false

      - name: Read Changelog
        id: read_changelog
        uses: juliangruber/read-file-action@v1
        with:
          path: CHANGELOG.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.read_version.outputs.value }}
          body_path: CHANGELOG.md
          name: "${TAG} Release"
          make_latest: true
          files: |
            StaTech_Industry-${{ steps.read_version.outputs.value }}.zip
            StaTech_Industry_Server-${{ steps.read_version.outputs.value }}.zip

      - name: Upload to CurseForge
        uses: henkelmax/upload-curseforge-modpack-action@v1.0.0
        with:
          api-token: ${{ secrets.CF_API_TOKEN }}
          project-id: '1605376'
          modpack-path: 'StaTech_Industry-${{ steps.read_version.outputs.value }}.zip'
          modpack-server-path: 'StaTech_Industry_Server-${{ steps.read_version.outputs.value }}.zip'
          changelog: ${{ steps.read_changelog.outputs.content }}
          changelog-format: 'markdown'
          game-version: '1.21.1'
          display-name: 'StaTech Industry ${{ steps.read_version.outputs.value }}'
          server-display-name: 'StaTech Industry Server ${{ steps.read_version.outputs.value }}'
          release-type: 'release'

      - name: Delete Build File
        uses: JesseTG/rm@v1.0.3
        with:
          path: 'StaTech_Industry-${{ steps.read_version.outputs.value }}.zip'

      - name: Delete Server Build File
        uses: JesseTG/rm@v1.0.3
        with:
          path: 'StaTech_Industry_Server-${{ steps.read_version.outputs.value }}.zip'
  
